site_name: CENG & SWE Ders NotlarÄ±
site_url: https://okancengswe.github.io/lecture-notes/
repo_url: https://github.com/okancengswe/lecture-notes
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: overrides
  language: tr
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
  palette:
    primary: indigo
    accent: indigo

plugins:
  - search

nav:
  - Ana Sayfa: index.md
  - Ortak:
      - 'Staj': common/staj.md

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.tasklist:
      custom_checkbox: true
      
extra_javascript:
#  - sw-register.js
